### ISSUE TITLE
openwrt路由运行zqhong的finalspeed命令行版报错

### ISSUE THREAD

**Issue by allenkey666** [d1sm/finalspeed#23]
Openwrt是基于linux的路由器。
如果可以，就能做到所有客户端零配置了。

**Comment by allenkey666** [comment]
我在openwrt上装了jamvm & libpcap，其中jamvm支持java 1.5.0，具体版本信息如下。
helloword已经成功运行，但是运行zqhong的finalspeed命令行版报错，看上去像其中GUI的代码没有删除。求指点。。。

# 

HelloWorldJamVM.class 源码：

class HelloWorldJamVM {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}

# 

jamvm信息：

root@TL-WR720N:~/finalspeed# jamvm -version
java version "1.5.0"
JamVM version 2.0.0
Copyright (C) 2003-2014 Robert Lougher rob@jamvm.org.uk

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Build information:

Execution Engine: direct-threaded interpreter with stack-caching
Compiled with: gcc 4.8.3

Boot Library Path: /usr/lib/classpath
Boot Class Path: /usr/share/jamvm/classes.zip:/usr/share/classpath/glibj.zip

# 

成功运行hello world

root@TL-WR720N:~/finalspeed# jamvm HelloWorldJamVM
hello world

# 

运行 zqhong的finalspeed命令行版报错

root@TL-WR720N:~/finalspeed# jamvm -jar client.jar
System: linux 3.18.20
java.lang.reflect.InvocationTargetException
   at java.lang.reflect.VMMethod.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:327)
   at jamvm.java.lang.JarLauncher.main(JarLauncher.java:50)
Caused by: java.awt.AWTError: Cannot load AWT toolkit: gnu.java.awt.peer.gtk.GtkToolkit
   at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:607)
   at javax.swing.plaf.basic.BasicLookAndFeel.initialize(BasicLookAndFeel.java:1720)
   at javax.swing.UIManager.setLookAndFeel(UIManager.java:912)
   at javax.swing.UIManager.<clinit>(UIManager.java:245)
   at javax.swing.JLabel.updateUI(JLabel.java:536)
   at javax.swing.table.DefaultTableCellRenderer.updateUI(DefaultTableCellRenderer.java:119)
   at javax.swing.JLabel.<init>(JLabel.java:507)
   at javax.swing.JLabel.<init>(JLabel.java:429)
   at javax.swing.table.DefaultTableCellRenderer.<init>(DefaultTableCellRenderer.java:86)
   at javax.swing.table.JTableHeader.createDefaultRenderer(JTableHeader.java:893)
   at javax.swing.table.JTableHeader.initializeLocalVars(JTableHeader.java:1053)
   at javax.swing.table.JTableHeader.<init>(JTableHeader.java:666)
   at javax.swing.JTable.createDefaultTableHeader(JTable.java:2800)
   at javax.swing.JTable.initializeLocalVars(JTable.java:2672)
   at javax.swing.JTable.<init>(JTable.java:2637)
   at javax.swing.JTable.<init>(JTable.java:2546)
   at net.fs.client.MapRuleListTable.<init>(MapRuleListTable.java:26)
   at net.fs.client.ClientNoUI.run(ClientNoUI.java:26)
   at net.fs.client.FSClient.main(FSClient.java:9)
   at java.lang.reflect.VMMethod.invoke(Native Method)
   ...2 more
Caused by: java.lang.UnsatisfiedLinkError: Native library `gtkpeer' not found (as file`libgtkpeer.so') in gnu.classpath.boot.library.path and java.library.path
   at java.lang.Runtime.loadLibrary(Runtime.java:763)
   at java.lang.System.loadLibrary(System.java:671)
   at gnu.java.awt.peer.gtk.GtkToolkit.<clinit>(GtkToolkit.java:177)
   at java.lang.VMClass.forName(Native Method)
   at java.lang.Class.forName(Class.java:233)
   at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:583)
   ...21 more

**Comment by allenkey666** [comment]
我感觉只要去除awt swing这些gui的类，然后用java 1.5重新编译一下，应该就能运行了，请问有大神帮忙吗？

**Comment by loyle5** [comment]
马克一下 万一解决了呢？

**Comment by heistrock** [comment]
马克一下，万一解决了呢？哈哈哈哈哈哈

**Comment by huangya90** [comment]
mark.

**Comment by fly9i** [comment]
在作者的基础上简单改了一个，主要是删了删swing依赖，无法运行有界面版本: https://github.com/fly9i/finalspeed

**Comment by lersh** [comment]
@bettermanbao  请问你的jamvm是怎么配置的啊，我在小米路由mini上配置jamvm总是不成功，运行时提示Exception occurred while printing exception (java/lang/NoClassDefFoundError)...
Original exception was java/lang/UnsatisfiedLinkError
能说说你是怎么配置的吗
