### ISSUE TITLE
Mac OSX 10.11.3  去除了ipfw，替换成了pf，每次启动报错

### ISSUE THREAD

**Issue by neohob** [d1sm/finalspeed#31]
System: mac os x 10.11.3
java.io.IOException: Cannot run program "ipfw": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
    at java.lang.Runtime.exec(Runtime.java:617)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:388)
    at net.fs.client.ClientUI.checkFireWallOn(ClientUI.java:558)
    at net.fs.client.ClientUI.<init>(ClientUI.java:438)
    at net.fs.client.FSClient.main(FSClient.java:8)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
    ... 6 more

**Comment by d1sm** [comment]
只是检测,不影响,不用理会
