### ISSUE TITLE
Ubuntu 15.10 启动报错

### ISSUE THREAD

**Issue by XGFan** [d1sm/finalspeed#4]
```
System Name: linux
Listen udp port: 1150
Listen tcp port: 1150
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "pool-1-thread-1" java.lang.Error: 

There is an incompatible JNA native library installed on this system
/usr/java/packages/lib/i386:/usr/lib/i386-linux-gnu/jni:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/lib/jni:/lib:/usr/lib.
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

    at com.sun.jna.Native.<clinit>(Native.java:146)
    at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
    at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
    at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
    at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
    at net.fs.cap.CapEnv.detectInterface(CapEnv.java:261)
    at net.fs.cap.CapEnv.initInterface(CapEnv.java:196)
    at net.fs.cap.CapEnv.init(CapEnv.java:102)
    at net.fs.rudp.Route.<init>(Route.java:103)
    at net.fs.server.FSServer$1.run(FSServer.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

环境是DigitalOcean Ubuntu 15.10 (GNU/Linux 3.16.0-28-generic i686)
我自己装过openJdk

**Comment by d1sm** [comment]
可能java版本太低

**Comment by XGFan** [comment]
我装的是Openjdk 8

通过我的 Moto X Style 发送

2015年12月29日 22:07于 wntr notifications@github.com写道：
可能java版本太低

---

**Comment by XGFan** [comment]
```
OpenJDK Client VM (build 24.91-b01, mixed mode, sharing)
 Run java success
```

安装时无报错，这是安装途中给出的JVM信息。

**Comment by d1sm** [comment]
卸载java,重新一键安装.
