### ISSUE TITLE
debian7重启报错

### ISSUE THREAD

**Issue by lostwind** [d1sm/finalspeed#44]
Exception in thread "pool-1-thread-1" java.lang.UnsatisfiedLinkError: Unable to load library 'pcap': Native library (linux-x86/libpcap.so) not found in resource path ([file:/fs/fs.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:337)
        at com.sun.jna.Function.getFunction(Function.java:83)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:41)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
        at net.fs.cap.CapEnv.detectInterface(CapEnv.java:264)
        at net.fs.cap.CapEnv.initInterface(CapEnv.java:196)
        at net.fs.cap.CapEnv.init(CapEnv.java:102)
        at net.fs.rudp.Route.<init>(Route.java:103)
        at net.fs.server.FSServer$1.run(FSServer.java:76)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)

**Comment by d1sm** [comment]
重装libpcap
