### ISSUE TITLE
centos服务器端安装失败

### ISSUE THREAD

**Issue by foreverxyz** [d1sm/finalspeed#45]
按照教程一步安装，安装过程出现如下提示：
usage: kill [ -s signal | -p ] [ -a ] pid ...
       kill -l [ signal ]
FinalSpeed start,log file: /fs/server.log

FinalSpeed server starting... 
System Name: linux
Listen udp port: 150
Listen tcp port: 150
Exception in thread "pool-1-thread-1" java.lang.UnsatisfiedLinkError: /tmp/jna-3506402/jna3254149984668182924.tmp: /tmp/jna-3506402/jna3254149984668182924.tmp: 无法从共享目标中映射段: 不允许的操作
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:763)
    at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:738)
    at com.sun.jna.Native.<clinit>(Native.java:131)
    at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
    at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
    at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
    at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
    at net.fs.cap.CapEnv.detectInterface(CapEnv.java:264)
    at net.fs.cap.CapEnv.initInterface(CapEnv.java:196)
    at net.fs.cap.CapEnv.init(CapEnv.java:102)
    at net.fs.rudp.Route.<init>(Route.java:103)
    at net.fs.server.FSServer$1.run(FSServer.java:76)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
运行 tail -f 出现如下：
tail -f /fs/server.log
    at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
    at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
    at net.fs.cap.CapEnv.detectInterface(CapEnv.java:264)
    at net.fs.cap.CapEnv.initInterface(CapEnv.java:196)
    at net.fs.cap.CapEnv.init(CapEnv.java:102)
    at net.fs.rudp.Route.<init>(Route.java:103)
    at net.fs.server.FSServer$1.run(FSServer.java:76)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java安装应该是正常的，
 java -version
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
麻烦给看下是怎么回事？

**Comment by d1sm** [comment]
卸载java ,手动安装其他版本jdk

**Comment by foreverxyz** [comment]
已经试着卸载后重新安装，失败。然后卸载，手动从官网下载然后安装，但是安装不成功。能不能麻烦给推荐个java版本，或者给个下载链接？谢谢
