### ISSUE TITLE
tcp连接超时关闭

### ISSUE THREAD

**Issue by lersh** [d1sm/finalspeed#52]
接收第三次握手  ident 9624
[Ethernet Header (14 bytes)]
  Destination address: 56:00:00:17:12:47
  Source address: fe:00:00:17:12:47
  Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
  Version: 4 (IPv4)
  IHL: 5 (20 [bytes])
  TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
  Total length: 40 [bytes]
  Identification: 9624
  Flags: (Reserved, Don't Fragment, More Fragment) = (false, true, false)
  Fragment offset: 0 (0 [bytes])
  TTL: 46
  Protocol: 6 (TCP)
  Header checksum: 0x8919
  Source address: /210.5.145.58
  Destination address: /45.32.13.191
[TCP Header (20 bytes)]
  Source port: 39828 (unknown)
  Destination port: 150 (SQL-NET)
  Sequence Number: 4064126487
  Acknowledgment Number: 1973492846
  Data Offset: 5 (20 [bytes])
  Reserved: 0
  URG: false
  ACK: true
  PSH: false
  RST: false
  SYN: false
  FIN: false
  Window: 65535
  Checksum: 0x4b26
  Urgent Pointer: 0

超时关闭client 210.5.145.58:39828 Wed Mar 23 07:17:47 UTC 2016

用UDP就没问题，但是公司网络UDP会被封锁

**Comment by lersh** [comment]
我用java版看了下，貌似是创建隧道失败了
System: windows 10 10.0
Network Interface List:
  Microsoft   \Device\NPF_{40DFBC48-9074-463C-BF96-F293C68CFEA7}
  Intel(R) Ethernet Connection (3) I218-LM   \Device\NPF_{6334A7B5-9718-4D7D-828D-4499AEFAA9D8}
  Oracle   \Device\NPF_{ECD43984-DADD-40B4-AED1-6EEDA4A3B4C1}
Selected Network Interface:
  Intel(R) Ethernet Connection (3) I218-LM   \Device\NPF_{6334A7B5-9718-4D7D-828D-4499AEFAA9D8}
发送第一次握手  ident 14788
[Ethernet Header (14 bytes)]
  Destination address: 20:76:93:3d:0d:fd
  Source address: 20:47:47:b9:16:27
  Type: 0x0800 (IPv4)
[IPv4 Header (20 bytes)]
  Version: 4 (IPv4)
  IHL: 5 (20 [bytes])
  TOS: [precedence: 0 (Routine)] [tos: 0 (Default)] [mbz: 0]
  Total length: 52 [bytes]
  Identification: 14788
  Flags: (Reserved, Don't Fragment, More Fragment) = (false, true, false)
  Fragment offset: 0 (0 [bytes])
  TTL: 64
  Protocol: 6 (TCP)
  Header checksum: 0x039e
  Source address: /192.168.1.219
  Destination address: /45.32.13.191
[TCP Header (32 bytes)]
  Source port: 65127 ()
  Destination port: 150 ()
  Sequence Number: 782061629
  Acknowledgment Number: 0
  Data Offset: 8 (32 [bytes])
  Reserved: 0
  URG: false
  ACK: false
  PSH: false
  RST: false
  SYN: true
  FIN: false
  Window: 65535
  Checksum: 0xf3eb
  Urgent Pointer: 0
  Option: [Kind: 2 (Maximum Segment Size)] [Length: 4 bytes] [Maximum Segment Size: 1440 bytes]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 3 (Window Scale)] [Length: 3 bytes] [Shift Count: 6]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 4 (SACK Permitted)] [Length: 2 bytes]

java.lang.Exception: 创建隧道失败!
        at net.fs.cap.CapEnv.createTcpTun_Client(CapEnv.java:465)
        at net.fs.cap.VDatagramSocket.tryConnectTun_Client(VDatagramSocket.java:84)
        at net.fs.cap.VDatagramSocket.send(VDatagramSocket.java:53)
        at net.fs.rudp.Route.sendPacket(Route.java:272)
        at net.fs.rudp.ClientControl.sendPacket(ClientControl.java:125)
        at net.fs.rudp.Sender.sendPacket(Sender.java:299)
        at net.fs.rudp.Sender.send(Sender.java:295)
        at net.fs.rudp.Sender.sendDataMessage(Sender.java:184)
        at net.fs.rudp.Sender.sendNata(Sender.java:123)
        at net.fs.rudp.Sender.sendData(Sender.java:78)
        at net.fs.rudp.UDPOutputStream.write(UDPOutputStream.java:23)
        at net.fs.client.PortMapProcess.<init>(PortMapProcess.java:65)
        at net.fs.client.PortMapManager$1$1.run(PortMapManager.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.io.IOException: 隧道不存在!  thread 3 /45.32.13.191:150
        at net.fs.cap.VDatagramSocket.send(VDatagramSocket.java:67)
        at net.fs.rudp.Route.sendPacket(Route.java:272)
        at net.fs.rudp.ClientControl.sendPacket(ClientControl.java:125)
        at net.fs.rudp.Sender.sendPacket(Sender.java:299)
        at net.fs.rudp.Sender.send(Sender.java:295)
        at net.fs.rudp.Sender.sendDataMessage(Sender.java:184)
        at net.fs.rudp.Sender.sendNata(Sender.java:123)
        at net.fs.rudp.Sender.sendData(Sender.java:78)
        at net.fs.rudp.UDPOutputStream.write(UDPOutputStream.java:23)
        at net.fs.client.PortMapProcess.<init>(PortMapProcess.java:65)
        at net.fs.client.PortMapManager$1$1.run(PortMapManager.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

服务器是没问题的，我在家里的mac电脑上可以使用tcp方式连接
