### ISSUE TITLE
客户端150端口超时关闭，mac os x 10.11.4

### ISSUE THREAD

**Issue by Geng-G-Razor** [d1sm/finalspeed#57]
从来就没成功过，折腾好久了，应该没有配置错。
Cannot run program "ipfw": error=2, No such file or directory
System: mac os x 10.11.4
java.io.IOException: Cannot run program "ipfw": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:388)
    at net.fs.client.ClientUI.checkFireWallOn(ClientUI.java:558)
    at net.fs.client.ClientUI.<init>(ClientUI.java:438)
    at net.fs.client.FSClient.main(FSClient.java:8)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 6 more
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
网络接口列表10:
     en0
     awdl0
     bridge0
     en1
     p2p0
     lo0
自动选择网络接口:
     en0
超时关闭client 23.**_.**_.199:150 Thu Mar 31 09:56:48 HKT 2016
超时关闭client 23.**_.**_.199:150 Thu Mar 31 10:07:07 HKT 2016

**Comment by bitraft** [comment]
最好可以选择泽网卡，在mac上被禁用的网卡都自己选上了。

macOS 10.10后用pfctl代替ipfw了
