### ISSUE TITLE
mac os x 10.11.5 链接失败

### ISSUE THREAD

**Issue by willin** [d1sm/finalspeed#70]
```
System: mac os x 10.11.5


[TCP Header (32 bytes)]
  Source port: 27728 ()
  Destination port: 8888 ()
  Sequence Number: 1407152676
  Acknowledgment Number: 0
  Data Offset: 8 (32 [bytes])
  Reserved: 0
  URG: false
  ACK: false
  PSH: false
  RST: false
  SYN: true
  FIN: false
  Window: 65535
  Checksum: 0xe61e
  Urgent Pointer: 0
  Option: [Kind: 2 (Maximum Segment Size)] [Length: 4 bytes] [Maximum Segment Size: 1440 bytes]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 3 (Window Scale)] [Length: 3 bytes] [Shift Count: 6]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 1 (No Operation)]
  Option: [Kind: 4 (SACK Permitted)] [Length: 2 bytes]
java.lang.Exception: 创建隧道失败!
    at net.fs.cap.CapEnv.createTcpTun_Client(CapEnv.java:459)
    at net.fs.cap.VDatagramSocket.tryConnectTun_Client(VDatagramSocket.java:84)
    at net.fs.cap.VDatagramSocket.send(VDatagramSocket.java:53)
    at net.fs.rudp.Route.sendPacket(Route.java:272)
    at net.fs.rudp.ClientControl.sendPacket(ClientControl.java:125)
    at net.fs.rudp.ClientControl.sendPingMessage(ClientControl.java:189)
    at net.fs.rudp.ClientManager.scanClientControl(ClientManager.java:54)
    at net.fs.rudp.ClientManager$1.run(ClientManager.java:38)
```

**Comment by willin** [comment]
还有开机启动勾选了无用

**Comment by ChinW** [comment]
同样的症状，1.2，1.0版本都试过了，一键安装包方式，vps也重装了一次，

iptables 如下

```
root@ubuntu:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       tcp  --  anywhere             anywhere             tcp dpt:150 /* tcptun_fs_server */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:150 /* udptun_fs_server */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
root@ubuntu:~#
```

希望得到一些思路，thx
