### ISSUE TITLE
不知道这个还有没有在维护 啊？

### ISSUE THREAD

**Issue by Jandaes** [d1sm/finalspeed#82]

**Comment by jackRoadOnTop** [comment]
感觉没有

**Comment by Jandaes** [comment]
好吧、那这个出问题就出问题了

**Comment by jackRoadOnTop** [comment]
大家可以讨论，遇到什么问题了？

**Comment by winhkey** [comment]
昨天开始一启动就报空指针异常
java.lang.NullPointerException
	at net.fs.client.ClientUI.<init>(ClientUI.java:302)
	at net.fs.client.FSClient.main(FSClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
